import mongoose, { Document, Schema } from 'mongoose';

export interface IFinanceSettings extends Document {
    key: 'default'; // singleton
    defaultCurrency: string;
    requireApprovalForExpense: boolean;
    requireApprovalForIncome: boolean;
    enableBudgets: boolean;
    enableRecurringEngine: boolean;
    receiptRequiredAboveAmount: number;
    exportFooterNote: string;
    smsCostPerMessageBDT: number;
    emailCostPerMessageBDT: number;
    costCenters: string[];
    updatedAt: Date;
    lastEditedByAdminId?: mongoose.Types.ObjectId;
}

const FinanceSettingsSchema = new Schema<IFinanceSettings>(
    {
        key: { type: String, default: 'default', unique: true },
        defaultCurrency: { type: String, default: 'BDT', trim: true },
        requireApprovalForExpense: { type: Boolean, default: true },
        requireApprovalForIncome: { type: Boolean, default: false },
        enableBudgets: { type: Boolean, default: true },
        enableRecurringEngine: { type: Boolean, default: true },
        receiptRequiredAboveAmount: { type: Number, default: 500, min: 0 },
        exportFooterNote: { type: String, trim: true, default: 'Generated by CampusWay Finance Center' },
        smsCostPerMessageBDT: { type: Number, default: 0.35, min: 0 },
        emailCostPerMessageBDT: { type: Number, default: 0.05, min: 0 },
        costCenters: [{ type: String, trim: true }],
        lastEditedByAdminId: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    },
    { timestamps: true, collection: 'finance_settings' }
);

export default mongoose.model<IFinanceSettings>('FinanceSettings', FinanceSettingsSchema);
