export type AdminBindingStatus = 'active' | 'duplicate' | 'removed';

export type AdminBindingField = {
    id: string;
    uiLocation: string;
    fieldLabel: string;
    dbModel: string;
    dbKeyPath: string;
    apiMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
    apiEndpoint: string;
    requestBody: string;
    responsePath: string;
    invalidateKeys: string[];
    status: AdminBindingStatus;
    notes?: string;
};

/**
 * Canonical field-level binding registry.
 * `{admin}` means either `/api/admin` or `/api/campusway-secure-admin`.
 */
export const adminBindingsRegistry: AdminBindingField[] = [
    {
        id: 'site.branding',
        uiLocation: 'Settings > Site Settings > Identity',
        fieldLabel: 'websiteName,motto,metaTitle,metaDescription,logo,favicon',
        dbModel: 'WebsiteSettings',
        dbKeyPath: 'websiteName,motto,metaTitle,metaDescription,logo,favicon',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/home/settings',
        requestBody: 'FormData fields',
        responsePath: 'settings.*',
        invalidateKeys: ['public_settings', 'site_settings', 'home', 'header', 'footer'],
        status: 'active',
    },
    {
        id: 'site.contact',
        uiLocation: 'Settings > Site Settings > Contact',
        fieldLabel: 'contactEmail,contactPhone',
        dbModel: 'WebsiteSettings',
        dbKeyPath: 'contactEmail,contactPhone',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/home/settings',
        requestBody: 'FormData.contactEmail,FormData.contactPhone',
        responsePath: 'settings.contactEmail,settings.contactPhone',
        invalidateKeys: ['public_settings', 'site_settings', 'home'],
        status: 'active',
    },
    {
        id: 'site.theme_and_pricing',
        uiLocation: 'Settings > Site Settings > Theme/UI + Pricing',
        fieldLabel: 'theme.*,socialUi.*,pricingUi.*',
        dbModel: 'WebsiteSettings',
        dbKeyPath: 'theme.*,socialUi.*,pricingUi.*',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/home/settings',
        requestBody: 'FormData.theme,socialUi,pricingUi',
        responsePath: 'settings.theme,settings.socialUi,settings.pricingUi',
        invalidateKeys: ['public_settings', 'site_settings', 'plans'],
        status: 'active',
    },
    {
        id: 'site.subscription_page',
        uiLocation: 'Settings > Site Settings > Subscription Page',
        fieldLabel: 'subscriptionPageTitle,subscriptionPageSubtitle,subscriptionDefaultBannerUrl,subscriptionLoggedOutCtaMode',
        dbModel: 'WebsiteSettings',
        dbKeyPath: 'subscriptionPageTitle,subscriptionPageSubtitle,subscriptionDefaultBannerUrl,subscriptionLoggedOutCtaMode',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/home/settings',
        requestBody: 'FormData.subscriptionPage*',
        responsePath: 'settings.subscriptionPage*',
        invalidateKeys: ['public_settings', 'site_settings', 'plans', 'home'],
        status: 'active',
    },
    {
        id: 'social.links.crud',
        uiLocation: 'Settings > Site Settings > Social Links Manager',
        fieldLabel: 'platformName,targetUrl,iconUploadOrUrl,description,enabled,placements[]',
        dbModel: 'SiteSettings',
        dbKeyPath: 'socialLinks[].platform,url,icon,description,enabled,placements[]',
        apiMethod: 'POST',
        apiEndpoint: '/api/{admin}/social-links',
        requestBody: '{platformName,targetUrl,iconUploadOrUrl,description,enabled,placements}',
        responsePath: 'items[]',
        invalidateKeys: ['public_settings', 'home', 'footer', 'header'],
        status: 'active',
    },
    {
        id: 'home.sections',
        uiLocation: 'Settings > Home Control > Section Visibility',
        fieldLabel: 'sectionVisibility.*',
        dbModel: 'HomeSettings',
        dbKeyPath: 'sectionVisibility.*',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/home-settings',
        requestBody: 'sectionVisibility',
        responsePath: 'homeSettings.sectionVisibility',
        invalidateKeys: ['home', 'home_settings', 'universityCategories'],
        status: 'active',
    },
    {
        id: 'home.highlighted_categories',
        uiLocation: 'Settings > Home Control > Highlighted Categories',
        fieldLabel: 'category,order,enabled,badgeText',
        dbModel: 'HomeSettings',
        dbKeyPath: 'highlightedCategories[]',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/home-settings',
        requestBody: 'highlightedCategories[]',
        responsePath: 'homeSettings.highlightedCategories[]',
        invalidateKeys: ['home', 'home_settings', 'universityCategories'],
        status: 'active',
    },
    {
        id: 'home.featured_universities',
        uiLocation: 'Settings > Home Control > Featured Universities',
        fieldLabel: 'universityId,order,enabled,badgeText',
        dbModel: 'HomeSettings',
        dbKeyPath: 'featuredUniversities[]',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/home-settings',
        requestBody: 'featuredUniversities[]',
        responsePath: 'homeSettings.featuredUniversities[]',
        invalidateKeys: ['home', 'home_settings', 'universities', 'universityCategories'],
        status: 'active',
    },
    {
        id: 'home.default_university_logo',
        uiLocation: 'Settings > Home Control > University Card Config',
        fieldLabel: 'Default University Logo',
        dbModel: 'HomeSettings',
        dbKeyPath: 'universityCardConfig.defaultUniversityLogo',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/home-settings',
        requestBody: 'universityCardConfig.defaultUniversityLogo',
        responsePath: 'homeSettings.universityCardConfig.defaultUniversityLogo',
        invalidateKeys: ['home', 'home_settings', 'universities'],
        status: 'active',
    },
    {
        id: 'plans.crud',
        uiLocation: 'Admin Subscription Plans',
        fieldLabel: 'name,code,type,priceBDT,durationDays,features,tags,cta,enabled,isFeatured',
        dbModel: 'SubscriptionPlan',
        dbKeyPath: 'name,code,type,priceBDT,durationDays,features,tags,contactCtaLabel,contactCtaUrl,enabled,isFeatured',
        apiMethod: 'POST',
        apiEndpoint: '/api/{admin}/subscription-plans',
        requestBody: 'plan payload',
        responsePath: 'item',
        invalidateKeys: ['plans', 'home', 'student_me'],
        status: 'active',
    },
    {
        id: 'plans.reorder',
        uiLocation: 'Admin Subscription Plans > List',
        fieldLabel: 'display order',
        dbModel: 'SubscriptionPlan',
        dbKeyPath: 'displayOrder,sortOrder,priority',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/subscription-plans/reorder',
        requestBody: '{order:[id...]}',
        responsePath: 'message',
        invalidateKeys: ['plans', 'home', 'student_me'],
        status: 'active',
    },
    {
        id: 'news.settings.core',
        uiLocation: 'Settings > Site Settings > News Settings',
        fieldLabel: 'pageTitle,pageSubtitle,headerBannerUrl,defaultBannerUrl,defaultThumbUrl,defaultSourceIconUrl',
        dbModel: 'NewsSystemSettings',
        dbKeyPath: 'config.pageTitle,config.pageSubtitle,config.headerBannerUrl,config.defaultBannerUrl,config.defaultThumbUrl,config.defaultSourceIconUrl',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/news/settings',
        requestBody: 'news settings payload',
        responsePath: 'settings',
        invalidateKeys: ['news_settings', 'news', 'home'],
        status: 'active',
    },
    {
        id: 'news.settings.workflow_ai_share',
        uiLocation: 'Settings > Site Settings > News Settings',
        fieldLabel: 'workflow.*,aiSettings.*,shareTemplates.*,share.shareButtons.*',
        dbModel: 'NewsSystemSettings',
        dbKeyPath: 'config.workflow.*,config.aiSettings.*,config.shareTemplates.*,config.share.shareButtons.*',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/news/settings',
        requestBody: '{workflow,aiSettings,shareTemplates,share}',
        responsePath: 'settings.workflow,settings.aiSettings,settings.shareTemplates',
        invalidateKeys: ['news_settings', 'news', 'home'],
        status: 'active',
    },
    {
        id: 'news.rss_sources',
        uiLocation: 'Admin News > Sources',
        fieldLabel: 'name,feedUrl,iconUrl,categoryDefault,tagsDefault,fetchIntervalMin,maxItemsPerFetch,isActive',
        dbModel: 'NewsSource',
        dbKeyPath: 'name,feedUrl,iconUrl,categoryDefault,tagsDefault,fetchIntervalMin,maxItemsPerFetch,isActive',
        apiMethod: 'POST',
        apiEndpoint: '/api/{admin}/news/sources',
        requestBody: 'source payload',
        responsePath: 'item',
        invalidateKeys: ['news_settings', 'news', 'home'],
        status: 'active',
    },
    {
        id: 'exam.gating.subscription',
        uiLocation: 'Admin Dashboard > Exams > Create/Edit',
        fieldLabel: 'Allowed Plan Codes',
        dbModel: 'Exam',
        dbKeyPath: 'accessControl.allowedPlanCodes[]',
        apiMethod: 'POST',
        apiEndpoint: '/api/{admin}/exams',
        requestBody: 'accessControl.allowedPlanCodes[]',
        responsePath: 'exam.accessControl.allowedPlanCodes[]',
        invalidateKeys: ['home'],
        status: 'active',
        notes: 'Subscription-required behavior is derived from this exam-level access control.',
    },
    {
        id: 'exam.gating.profile_score',
        uiLocation: 'Settings > Security Center > Site & Exam Protection',
        fieldLabel: 'requireProfileScoreForExam,profileScoreThreshold',
        dbModel: 'SecuritySettings',
        dbKeyPath: 'examProtection.requireProfileScoreForExam,examProtection.profileScoreThreshold',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/security-settings',
        requestBody: 'examProtection',
        responsePath: 'settings.examProtection',
        invalidateKeys: ['home', 'student_me'],
        status: 'active',
    },
    {
        id: 'students.import',
        uiLocation: 'Admin Students > Import Wizard',
        fieldLabel: 'file,mapping,defaults,commit',
        dbModel: 'StudentImportJob',
        dbKeyPath: 'rawRows,mapping,defaults,normalizedRows,validationSummary,commitSummary',
        apiMethod: 'POST',
        apiEndpoint: '/api/{admin}/students/import/init|:id/validate|:id/commit',
        requestBody: 'multipart file + {mapping,defaults}',
        responsePath: 'data.validationSummary,data.summary',
        invalidateKeys: ['students', 'student-groups', 'home'],
        status: 'active',
    },
    {
        id: 'students.groups',
        uiLocation: 'Admin Students > Groups',
        fieldLabel: 'name,slug,batchTag,description,isActive,meta + member assignment',
        dbModel: 'StudentGroup + StudentProfile',
        dbKeyPath: 'StudentGroup.* + StudentProfile.groupIds[]',
        apiMethod: 'POST',
        apiEndpoint: '/api/{admin}/student-groups + /api/{admin}/student-groups/:id',
        requestBody: 'group payload + {addStudentIds,removeStudentIds}',
        responsePath: 'item',
        invalidateKeys: ['students', 'student-groups', 'home'],
        status: 'active',
    },
    {
        id: 'support.tickets',
        uiLocation: 'Admin Support Center > Tickets',
        fieldLabel: 'status + reply',
        dbModel: 'SupportTicket',
        dbKeyPath: 'status,timeline[]',
        apiMethod: 'PATCH',
        apiEndpoint: '/api/{admin}/support-tickets/:id/status + /api/{admin}/support-tickets/:id/reply',
        requestBody: '{status} or {message}',
        responsePath: 'item.status,item.timeline',
        invalidateKeys: ['admin.support-tickets'],
        status: 'active',
    },
    {
        id: 'support.notices',
        uiLocation: 'Admin Support Center > Notices',
        fieldLabel: 'title,message,target,startAt,endAt,isActive',
        dbModel: 'AnnouncementNotice',
        dbKeyPath: 'title,message,target,targetIds,startAt,endAt,isActive',
        apiMethod: 'POST',
        apiEndpoint: '/api/{admin}/notices + /api/{admin}/notices/:id/toggle',
        requestBody: 'notice payload',
        responsePath: 'item',
        invalidateKeys: ['admin.support-notices', 'admin.support-tickets'],
        status: 'active',
    },
    {
        id: 'support.unread_badge',
        uiLocation: 'Admin Dashboard Summary',
        fieldLabel: 'Unread Support Messages',
        dbModel: 'SupportTicket (derived)',
        dbKeyPath: 'derived count',
        apiMethod: 'GET',
        apiEndpoint: '/api/{admin}/dashboard/summary',
        requestBody: 'n/a',
        responsePath: 'supportCenter.unreadMessages',
        invalidateKeys: ['admin.support-tickets'],
        status: 'active',
    },
    {
        id: 'security.core',
        uiLocation: 'Settings > Security Center',
        fieldLabel: 'passwordPolicy,loginProtection,session,adminAccess,siteAccess,examProtection,logging,rateLimit',
        dbModel: 'SecuritySettings',
        dbKeyPath: 'passwordPolicy.*,loginProtection.*,session.*,adminAccess.*,siteAccess.*,examProtection.*,logging.*,rateLimit.*',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/security-settings',
        requestBody: 'security payload',
        responsePath: 'settings',
        invalidateKeys: ['admin.security-settings', 'admin.runtime-settings'],
        status: 'active',
    },
    {
        id: 'security.runtime_flags',
        uiLocation: 'Settings > Security Center > Runtime Flags',
        fieldLabel: 'featureFlags.*',
        dbModel: 'SiteSettings',
        dbKeyPath: 'featureFlags.*',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/settings/runtime',
        requestBody: '{featureFlags:{...}}',
        responsePath: 'featureFlags',
        invalidateKeys: ['admin.runtime-settings'],
        status: 'active',
    },
    {
        id: 'logs.read_only',
        uiLocation: 'Settings > System Logs',
        fieldLabel: 'Audit log filters',
        dbModel: 'AuditLog',
        dbKeyPath: 'query-only',
        apiMethod: 'GET',
        apiEndpoint: '/api/{admin}/audit-logs',
        requestBody: 'query params',
        responsePath: 'logs[]',
        invalidateKeys: [],
        status: 'active',
        notes: 'Read-only module by design.',
    },
    {
        id: 'duplicate.quick_social_url_map',
        uiLocation: 'Settings > Site Settings (removed block)',
        fieldLabel: 'Quick Social URL Map',
        dbModel: 'WebsiteSettings',
        dbKeyPath: 'socialLinks.*',
        apiMethod: 'PUT',
        apiEndpoint: '/api/{admin}/home/settings',
        requestBody: 'socialLinks map',
        responsePath: 'settings.socialLinks',
        invalidateKeys: ['public_settings', 'home', 'footer', 'header'],
        status: 'removed',
        notes: 'Removed to prevent conflicting writes with Social Links Manager.',
    },
];

export const getActiveAdminBindings = (): AdminBindingField[] =>
    adminBindingsRegistry.filter((item) => item.status === 'active');

